### ISSUE TITLE
A new database issue on appveyor

### ISSUE THREAD

**Issue by rynowak** [aspnet/JitBench#43]
I've seen this issue running on appveyor, I haven't yet seen it on a local windows install.

```
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "MusicStore" requested by the login. The login failed.
Login failed for user 'APPVYR-WIN\appveyor'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__34.MoveNext()
ClientConnectionId:2e6c7daf-2faa-42b2-8cb1-489a353f9e01
Error Number:4060,State:1,Class:11
Server started in 5534ms
``

Tracking this since it doesn't cause the app to fail, it just seems to affect the startup time. 

I repeat, I have **only** seen this on appveyor.

**Comment by rynowak** [comment]
This is still happening but only in dev, not in 2.0.0/preview1 as of https://ci.appveyor.com/project/aspnetci/jitbench/build/1.0.71v

**Comment by rynowak** [comment]
This is resolved
