### ISSUE TITLE
MusicStore fails with System.Net.Http.HttpRequestException error

### ISSUE THREAD

**Issue by adiaaida** [aspnet/JitBench#80]
I'm trying to do some experiments, and started with just doing a stock build/run of MusicStore on Windows. After following all of the instructions, MusicStore fails to run with the following error:

```
PS C:\michelm\JitBench\src\MusicStore\bin\Release\netcoreapp2.1\publish> dotnet .\MusicStore.dll
Server started in 1062ms

Starting request to http://localhost:5000

Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MusicStore.Program.Main(String[] args) in C:\michelm\JitBench\src\MusicStore\Program.cs:line 62
```

**Comment by rynowak** [comment]
I got some help looking at this and there seems to be a legitimate issue: https://github.com/aspnet/KestrelHttpServer/issues/2241

**Comment by rynowak** [comment]
I think this should be fixed by https://github.com/aspnet/JitBench/pull/82 - could you pull latest and try again?

**Comment by adiaaida** [comment]
Checking it out now.

**Comment by adiaaida** [comment]
Yep. That works. Thanks so much for figuring this out!

**Comment by rynowak** [comment]
great!
